name: CI

on: [push, pull_request]

jobs:
  format:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: "1.10"

      - name: Check format
        run: mix format --check-formatted

  test:
    name: Test suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pair:
          - erlang: 22.3
            elixir: "1.10"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.pair.erlang }}
          elixir-version: ${{ matrix.pair.elixir }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
